#!/bin/sh

usage() {
	echo "Usage: ./GO_CAVE2_DZ [-b buffersize] [-i file] [-l file_l file_r]"
}

for var in "$@"
do
    args=`echo $args $var`
done

mpirun -np 3 --default-hostfile machine-local dzviewer -s desktop -n $args